# Generated by Django 3.1.7 on 2021-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
